import { faCode } from "@fortawesome/free-solid-svg-icons";

export const QuizData = [
  {
    id: 1,
    icon: faCode,
    title: "JavaScript Quiz",
    quizQuestions: [
      {
        id: 1,
        question: "What is JavaScript?",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 2,
        question: "What is JavaScript? 2",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 3,
        question: "What is JavaScript?3",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 4,
        question: "What is JavaScript?4",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 5,
        question: "What is JavaScript?5",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
    ],
  },
  {
    id: 2,
    icon: faCode,
    title: "JavaScript Quiz",
    quizQuestions: [
      {
        id: 1,
        question: "What is JavaScript?2",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 2,
        question: "What is JavaScript? 2",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 3,
        question: "What is JavaScript?3",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 4,
        question: "What is JavaScript?4",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 5,
        question: "What is JavaScript?5",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
    ],
  },
  {
    id: 3,
    icon: faCode,
    title: "JavaScript Quiz 3",
    quizQuestions: [
      {
        id: 1,
        question: "What is JavaScript?",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 2,
        question: "What is JavaScript? 2",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 3,
        question: "What is JavaScript?3",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 4,
        question: "What is JavaScript?4",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 5,
        question: "What is JavaScript?5",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
    ],
  },
  {
    id: 4,
    icon: faCode,
    title: "JavaScript Quiz 4",
    quizQuestions: [
      {
        id: 1,
        question: "What is JavaScript?",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 2,
        question: "What is JavaScript? 2",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 3,
        question: "What is JavaScript?3",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 4,
        question: "What is JavaScript?4",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
      {
        id: 5,
        question: "What is JavaScript?5",
        choices: [
          "A. To style HTML elements",
          "B. To add interactivity to web pages",
          "C. To define the structure of a web page",
          "D. To perform server-side operations",
        ],
        correctAnswer: 1,
        answeredResult: -1,
        statistics: {
          totalAttempt: 3,
          correctAttempts: 2,
          incorrectAttempts: 1,
        },
      },
    ],
  },
];
